# Generated by Django 3.1 on 2020-08-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200810_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='idno',
            new_name='Emp_id',
        ),
    ]
