# Generated by Django 3.1 on 2020-08-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200810_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Emp_id',
        ),
    ]
