# Generated by Django 3.0.8 on 2020-07-25 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=120)),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('Address', models.TextField(max_length=120)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.Usern')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.CharField(max_length=120, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.Usern')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2020, 7, 25, 19, 23, 44, 635731, tzinfo=utc))),
                ('date', models.DateField(default=datetime.datetime(2020, 7, 25, 19, 23, 44, 635731, tzinfo=utc))),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.Book')),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.Usern')),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.Status')),
            ],
        ),
    ]
