# Generated by Django 3.0.8 on 2020-07-25 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20200726_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 25, 20, 16, 43, 329187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 25, 20, 16, 43, 329187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='Design',
            field=models.CharField(max_length=520, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, max_length=520, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(blank=True, max_length=520, null=True),
        ),
    ]
