# Generated by Django 3.0.8 on 2020-07-26 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_auto_20200726_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 26, 7, 24, 12, 101894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 26, 7, 24, 12, 101894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='Design',
            field=models.TextField(max_length=520, null=True),
        ),
    ]
