# Generated by Django 2.2 on 2020-07-26 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_auto_20200726_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 26, 8, 39, 55, 504335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 26, 8, 39, 55, 503335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='Design',
            field=models.CharField(max_length=520, null=True),
        ),
    ]
