# Generated by Django 2.2 on 2020-07-27 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_auto_20200727_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 27, 15, 24, 12, 402652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 27, 15, 24, 12, 402652, tzinfo=utc)),
        ),
    ]
