# Generated by Django 2.2 on 2020-07-29 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_auto_20200727_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 10, 7, 47, 553210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='posts',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 29, 10, 7, 47, 553210, tzinfo=utc)),
        ),
    ]
